// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSl5ZzuzfxrmXFUpnQTiRM6o0vqhKCwso',
    appId: '1:170392361865:web:f4b70a5afa043176979f58',
    messagingSenderId: '170392361865',
    projectId: 'chatify-b629a',
    authDomain: 'chatify-b629a.firebaseapp.com',
    storageBucket: 'chatify-b629a.firebasestorage.app',
    measurementId: 'G-93Y1SSSFTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAclf2oF00V5JE8t358XiRkKkb4bxpNvY8',
    appId: '1:170392361865:android:3a58748e4ff672fb979f58',
    messagingSenderId: '170392361865',
    projectId: 'chatify-b629a',
    storageBucket: 'chatify-b629a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq4EB6nbtn-Djz5jFY266I2X_ue81DjxI',
    appId: '1:170392361865:ios:26eaaa6be3ea00a0979f58',
    messagingSenderId: '170392361865',
    projectId: 'chatify-b629a',
    storageBucket: 'chatify-b629a.firebasestorage.app',
    iosBundleId: 'com.example.chatifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq4EB6nbtn-Djz5jFY266I2X_ue81DjxI',
    appId: '1:170392361865:ios:26eaaa6be3ea00a0979f58',
    messagingSenderId: '170392361865',
    projectId: 'chatify-b629a',
    storageBucket: 'chatify-b629a.firebasestorage.app',
    iosBundleId: 'com.example.chatifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSl5ZzuzfxrmXFUpnQTiRM6o0vqhKCwso',
    appId: '1:170392361865:web:49896f586f0cbb2c979f58',
    messagingSenderId: '170392361865',
    projectId: 'chatify-b629a',
    authDomain: 'chatify-b629a.firebaseapp.com',
    storageBucket: 'chatify-b629a.firebasestorage.app',
    measurementId: 'G-1NPC3CX4L4',
  );
}
